calculations:
    kwHCost: 0.25
    endDate: 2014-07-01
    startDate: 2013-06-30

logging:
    level: INFO
    loggers:
      io.dropwizard: INFO
      au.com.privitar: DEBUG
    appenders:
      - type: console
        threshold: ALL
        target: stdout
        timeZone: UTC
